[package]
name = "testing"
version = "0.1.0"
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
edition = "2018"
publish =false

[lib]
proc-macro = true

[dependencies]
pmutil = { path = "../" }
proc-macro2 = "1"